DROP TABLE PERSON;
DROP TABLE PRODUCT;
DROP TABLE STOCK;

CREATE TABLE PERSON(
ID INT NOT NULL AUTO_INCREMENT,
EMAIL  VARCHAR(200) NOT NULL,
PASSWORD VARCHAR(200) NOT NULL,
TOKEN VARCHAR(200)  NOT NULL,
PRIMARY KEY (ID)
);
CREATE TABLE PRODUCT(
ID INT NOT NULL AUTO_INCREMENT,
PERSONID INT NOT NULL,
NAME NVARCHAR(200) NOT NULL,
PRICE FLOAT NOT NULL,
STOCK INT NOT NULL,
PRIMARY KEY (ID)
);
CREATE TABLE STOCK(
ID INT NOT NULL AUTO_INCREMENT,
PERSONID INT NOT NULL,
QUANTITY INT NOT NULL,
PRIMARY KEY (ID)
);